### ISSUE TITLE
Implement is_resource() and contents()

### ISSUE THREAD

**Issue by warsaw** [brettcannon/importlib_resources#35]
These methods are described in #26

**Comment by warsaw** [comment]
The signature for these two methods is:

```python
def contents(package : Package) -> Iterator[str]

def is_resource(package : Package, file_name : FileName) -> bool
```

Questions:

* Do we want support for these in the `ResourceReader` ABC?
* Should `contents() -> List[str]`?

**Comment by brettcannon** [comment]
* Changes to `ResourceReader` were covered as part of my proposal, so yes 😉 
* So I typed it that way in case the storage back-end being used made it costly to get the list, otherwise I don't care
