### ISSUE TITLE
Accept packages as well as package names?

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/importlib_resources#7]

**Comment by brettcannon** [comment]
I assume we would do:
```python
if hasattr(package, '__spec__'):
    package_name = package.__spec__.name
else:
    package_name = package
```
if we decided to support this.

**Comment by warsaw** [comment]
I guess we would have to do something different for Python 2.7 (since it doesn't have `__spec__`), but yep, that's essentially what I had in mind.

**Comment by brettcannon** [comment]
So the question is do we want to do this? 😄 I'm in support of it since it's an easy-enough nicety.

**Comment by warsaw** [comment]
Let's do it.  It's easy enough to back out before the first release if we get lots of complaints.
